name: CI

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go toolchain
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true

      - name: Set up Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Go dependencies
        working-directory: api
        run: go mod tidy

      - name: Run Go tests
        working-directory: api
        run: go test ./...

      - name: Run gofmt check
        working-directory: api
        run: test -z "$(gofmt -l ./cmd ./internal)"

      - name: Run forge tests
        working-directory: contracts
        run: |
          forge coverage
          forge snapshot

      - name: Lint Solidity using solhint
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g solhint@3.6.0
      - run: solhint "contracts/src/**/*.sol"
        working-directory: contracts

      - name: Build API Docker image
        run: docker build -t fiatrails-api ./api
